version: '3.8'

services:
  splunk:
    hostname: splunk-iso
    image: splunk/splunk:latest
    # platform required when running in a M1
    platform: linux/amd64
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunk123
    ports:
      - "8002:8000"
      - "8088:8088"
      - "8089:8089"
      - "9997:9997"
    volumes:
      - splunk-data:/opt/splunk/var
    networks:
      - lecastelet
      - splunk-net

volumes:
  splunk-data:

networks:
  lecastelet:
    driver: bridge
  splunk-net:
    external: true
